# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f8014090a2f0c9c8761e6377cf6ebfbc0b2b36013d8e7fc56d79952e077325462294fce7bb902ae5f8e50dfa897c648b488a6d05e717b4f1a9cad31b682ad1b

test:
  secret_key_base: 70bbe321e54b99902c98e69c166a23272716db06f321172135202cf6d0c0632a564dc19a726aeac1b58b4c24d5a6f888c1df66204a87ebacc8708e38a08e99c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
